project2_commerce/Commerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("auctions.urls")),
    path('users/', include("users.urls"))
]

project2_commerce/users/urls.py
from django.urls import path
from . import views

app_name= "users"
urlpatterns= [
    path('', views.index, name="index"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('register/', views.register, name="register"),
    path('changing/', views.changing, name="changing")
]

project2_commerce/users/models.py
from typing_extensions import Literal
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

project2_commerce/users/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import User
from django.db import IntegrityError
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
# Create your views here.

def index(request):
    if not request.user.is_authenticated:
        return render(request, "users/index.html")
    else:
        return HttpResponseRedirect(reverse("auctions:index"))

def login_view(request):
    if request.method== "POST":
        username= request.POST["username"]
        password= request.POST["password"]
        user= authenticate(request, username=username, password=password)
        if user is not None:
            login(request,user)
            return HttpResponseRedirect(reverse("users:index"))
        else:
            return render(request, "users/login.html", {
                'message': "Username Or Password Not Correct, Please Try Against!",
                'user': user
            })
    else:
        return render(request, "users/login.html")

def logout_view(request):
    logout(request)
    return render(request, "users/index.html", {
        'message': "Logged Out"
    }) 

def register(request):
    if request.method=="POST":
        first_name= request.POST["first"]
        last_name= request.POST["last"]
        email= request.POST["email"]
        username= request.POST["username"]
        password= request.POST["password"]
        confirmation= request.POST["confirmation"]
        if password!=confirmation:
            return render(request, "users/register.html", {
                'message': "Password Must Match confirmation"
            })
        try:
            user= User.objects.create_user(
                username= username,
                password= password,
                email= email,
                first_name= first_name,
                last_name= last_name
            )
            user.save()
        except IntegrityError:
            return render(request, "users/register.html", {
                'message': "Username Already Taken"
            })
        login(request,user)
        return HttpResponseRedirect(reverse("users:index"))
    else:
        return render(request, "users/register.html")

def changing(request):
    if request.method=="POST":
        password= request.POST["password"]
        new_password= request.POST["newpassword"]
        confirmation= request.POST["confirm"]
        user= authenticate(request, username= request.user.username, password= password)
        if user is None:
           return render(request, 'users/changing.html',{
                'message': 'Password not correctly!'
            })
        elif new_password!=confirmation:
            return render(request, 'users/changing.html',{
                'message': 'Confirmation must true!'
            })
        user.set_password(new_password)
        user.save()
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, 'users/changing.html')

project2_commerce/users/templates/users/changing.html
{% extends "users/layout.html" %}
{% block title %}
    <title>Change Password</title>
    <style>
        .changing{
            height: 13vh;
            width: 40vw;
            display: flex;
            flex-direction: row;
            justify-content: space-between;
        }

        .inp{
            height: 4vh;
            width: 15vw;
        }
    </style>
{% endblock %}

{% block body %}
    <h2>Changing Password:</h2>
    <h3>{{message}}</h3>
    <br>
    <form action="{% url 'users:changing' %}" method="post">
        {% csrf_token %}
        <p>Current Password: </p>
        <input type="password" name="password" id="password" class="inp">
    <div class="changing">
    <div>
        <p>New Password</p>
        <input type="password" name="newpassword" id="newpassword" class="inp">
    </div>
    <div>
        <p>Confirmation</p>
        <input type="password" name="confirm" id="confirm" class="inp">
    </div>
    </div>
        <input type="submit" value="Changing Password" style="margin-top: 20px; padding: 7px 10px;">
    </form>
{% endblock %}

project2_commerce/users/templates/users/index.html
{% extends "users/layout.html" %}
{% block title %}
    <title>Login | Register</title>
{% endblock %}

{% block body %}
    <h2 style="text-align: center;">Please, <a href="{% url 'users:login' %}">Login</a> to use this function</h2>
    <h2 style="text-align: center;"> If you have not already account, please <a href="{% url 'users:register' %}">Register</a> account</h2>
{% endblock %}

project2_commerce/users/templates/users/layout.html
{% extends "auctions/layout.html" %}

{% block title %}
    <title>Login | Register</title>
    {% block style %}
    {% endblock %}
{% endblock %}

{% block body %}
{% endblock %}

project2_commerce/users/templates/users/login.html
{% extends 'users/layout.html' %}

{% block title %}
    <title>Login</title>
    <style>
        .inp{
            height: 4vh;
            width: 15vw;
        }
    </style>
{% endblock %}

{% block body %}
    <h1>Login: </h1>
    <h2> {{message}} </h2>
    <form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
        <p>Username: </p>
        <input type="text" name="username" class="inp">
        <p>Password: </p>
        <input type="password" name="password" class="inp">
        <br>
        <input type="submit" value="Login" style="margin-top: 10px; padding: 7px 17px;">
    </form>
    <p>If you have not already account, please <a href="{% url 'users:register' %}">Register</a></p>
{% endblock %}

project2_commerce/users/templates/users/register.html
{% extends 'users/layout.html' %}

{% block title %}
    <title>Register</title>
    <style>
        .log{
            height: 4vh;
            width: 15vw;
        }

        .user{
            height: 13vh;
            width: 40vw;
            display: flex;
            flex-direction: row;
            justify-content: space-between;
        }

        .inp{
            height: 4vh;
            width: 15vw;
        }

    </style>
{% endblock %}

{% block body %}
    <h1>Register: </h1>
    <h2> {{message}} </h2>
    <form action="{% url 'users:register' %}" method="post">
    {% csrf_token %}
    <div class="user">
        <div>
            <p>First Name: </p>
            <input type="text" name="first" class="inp">
        </div>
        <div>
            <p>Last Name: </p>
            <input type="text" name="last" class="inp">
        </div>
    </div>
    <div class="user">
    <div>
        <p>Username: </p>
        <input type="text" name="username" class="inp">
    </div>
    <div>
        <p>Email: </p>
        <input type="email" name="email" class="inp">
    </div>
    </div>
    <div class="user">
    <div>
        <p>Password: </p>
        <input type="password" name="password" class="inp">
    </div>
    <div>
        <p>Confirmation: </p>
        <input type="password" name="confirmation" class="inp">
    </div>
    </div>
    <input type="submit" value="Register" style="margin-top: 20px; padding: 7px 15px;">
    </form>
{% endblock %}